---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 20
      semver-patch-days: 10
      semver-minor-days: 20
      semver-major-days: 30

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
