---
repos:
  # Python
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v7.0.0
    hooks:
      - id: pyproject-flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]

  # General
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.15.0
    hooks:
      - id: markdownlint_docker
        args: ['--style', '.markdownlint_style.rb']
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
